config/routes.rb
Rails.application.routes.draw do

  post 'payments/create'

  get 'products/special_offers'

  get 'products/our_offers'

  get 'products/not_public_offers'

  get 'products/user_offers'

  authenticate :user do
    resources :products, only: [:new, :create, :edit, :destroy]
  end

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => { :registrations => "user_registrations" }

  resources :users

  post 'messages/thank_you'

  get 'messages/new'

  get 'static_pages/repair'

  get 'static_pages/index'

  resources :products, only: [:index, :update, :show] do
    resources :comments
  end

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  root 'static_pages#index'

  mount ActionCable.server => '/cable'

  resources :orders, only:[:index, :show, :create, :destroy]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :product

  validates :body, :user, :product, presence: true
  validates :body, length: { in: 4..100 }
  validates :rating, numericality: { only_integer: true }

  after_create_commit { CommentUpdateJob.perform_later(self, @user) }

  self.per_page = 3

  def self.order_paginate(pages_param)
    page(pages_param).order("created_at DESC")
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @product = Product.find(params[:product_id])
    @comment = @product.comments.new(comment_params)
    @comment.user = current_user
    @user = request.env['warden'].user
    respond_to do |format|
      Rails.logger.debug(@comment.errors.inspect)
      if @comment.save
        #ActionCable.server.broadcast 'product_channel', comment: @comment
        format.html { redirect_to @product, notice: "Review was created successfully."}
        format.json { render :show, status: :created, location: @product }
        format.js
      else
        format.html { redirect_to @product, alert: "Review was not saved successfully. Make sure to enter your comment and rate this product."  }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      #redirect_to product_path(@product)
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    product = @comment.product
    @comment.destroy
    redirect_to product
  end

private

  def comment_params
    params.require(:comment).permit(:user_id, :body, :rating)
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="row">
  <hr>
  <p>
    <%= comment.user.first_name %>  <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small>
    <% if current_user && current_user.admin? %>
      <%= link_to ("<span><i class='fa fa-trash-o pull-right' aria-hidden='true'></i></span>").html_safe, product_comment_path(comment.product, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </p>
  <div class="rated" data-score="<%= comment.rating %>"></div>
  <p><%= comment.body %></p>
</div>

app/views/comments/create.js.erb
$("#new_comment").html("Thank you for your review!");

refreshRating();