config/routes.rb
Rails.application.routes.draw do

  post 'payments/create'

  get 'products/special_offers'

  get 'products/our_offers'

  get 'products/not_public_offers'

  get 'products/user_offers'

  authenticate :user do
    resources :products, only: [:new, :create, :edit, :destroy]
  end

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => { :registrations => "user_registrations" }

  resources :users

  post 'messages/thank_you'

  get 'messages/new'

  get 'static_pages/repair'

  get 'static_pages/index'

  resources :products, only: [:index, :update, :show] do
    resources :comments
  end

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  root 'static_pages#index'

  mount ActionCable.server => '/cable'

  resources :orders, only:[:index, :show, :create, :destroy]

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :orders
  has_many :products

#  scope :admin, -> { where( admin: true ) }
#  scope :member, -> { where( "user_id = #{current_user.id}" ) }

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  #before_filter
  load_and_authorize_resource

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        logger.info "if update **************"
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        logger.info "else update **************"
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name, class: "form-control input-md", autofocus: true, placeholder: :first_name %><br>
  </div>
  <div class="form-group">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name, class: "form-control input-md", autofocus: true, placeholder: :last_name %><br>
  </div>
  <div class="form-group">
    <%= f.label :email %><br>
    <%= f.text_field :email, class: "form-control input-md", autofocus: true, placeholder: :email %><br>
  </div>
  <div class="form-group">
    <%= f.label :password %><br>
    <%= f.text_field :password, class: "form-control input-md", autofocus: true, placeholder: :password %><br>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-default" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1 class="page-title">Edit Account Information</h1>
<%= render "shared/separator" %>
<div class="panel panel-default">
  <div class="panel-body">

    <%= render 'form' %>

    <%= link_to 'Show', @user, class: "scaffolded-link white" %> |
    <%= link_to 'Back', @user, class: "scaffolded-link white" %>
  </div><!-- panel-body -->
</div><!-- panel -->

app/views/users/index.html.erb
<h1 class="page-title">Bike Berlin Members</h1>

<%= render "shared/alert" %>
<div class="panel panel-default">
  <div class="panel-body">
    <table>
      <thead>
        <tr>
          <th>First name</th>
          <th>Last name</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.first_name %></td>
            <td><%= user.last_name %></td>
            <td><%= link_to 'Show', user %></td>
            <td><%= link_to 'Edit', edit_user_path(user) %></td>
            <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New User', new_user_path, class: "scaffolded-link white" %>
  </div><!-- panel-body -->
</div><!-- panel -->

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h1 class="page-title">Account Information</h1>
<%= render "shared/alert" %>
<%= render "shared/separator" %>
<div class="panel panel-default">
  <div class="panel-body">
    <p>
      <strong>First name:</strong>
      <%= @user.first_name %>
    </p>

    <p>
      <strong>Last name:</strong>
      <%= @user.last_name %>
    </p>

    <p>
      <strong>Email:</strong>
      <%= @user.email %>
    </p>


    <%= link_to 'Edit', edit_user_path(@user), class: "scaffolded-link white" %> |
    <%= link_to 'Back', request.referer.present? ? request.referer : static_pages_index_path, class: "scaffolded-link white" %>
  </div><!-- panel-body -->
</div><!-- panel -->