config/routes.rb
Rails.application.routes.draw do

  post 'payments/create'

  get 'products/special_offers'

  get 'products/our_offers'

  get 'products/not_public_offers'

  get 'products/user_offers'

  authenticate :user do
    resources :products, only: [:new, :create, :edit, :destroy]
  end

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => { :registrations => "user_registrations" }

  resources :users

  post 'messages/thank_you'

  get 'messages/new'

  get 'static_pages/repair'

  get 'static_pages/index'

  resources :products, only: [:index, :update, :show] do
    resources :comments
  end

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  root 'static_pages#index'

  mount ActionCable.server => '/cable'

  resources :orders, only:[:index, :show, :create, :destroy]

end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :name, :description, :image_url, :color, presence: true
  validates :name, length: { in: 4..21 }
  validates :description, length: { in: 4..150 }
  validates :price, numericality: { greater_than: 0, message: "must be a number greater than 0" }
  validates :image_url, :url => true
  belongs_to :user
  has_many :orders
  has_many :comments

  scope :special_offers, -> { where( special_offer: true ) }
  scope :not_public_offers, -> { where( public: false ) }
  scope :public_offers, -> { where( public: true ) }

  def self.search_production(search_term)
      where(public: true).where("name ilike ?", "%#{search_term}%")
  end

  def self.search_development(search_term)
    where(public: true).where("name LIKE ?", "%#{search_term}%")
  end

  def self.admin_created
    joins(:user).where( :users => {:admin => true} )
  end

  def self.current_user_created(current_id)
    joins(:user).where("user_id = #{current_id}")
  end

  def self.members_created
    joins(:user).where( :users => {:admin => false} )
  end

  def average_rating
    comments.average(:rating).to_f
  end


  def self.payment_process(payment_params, user)

      #@product = Product.find(params[:product_id])
      #params = payment_params.dup
      @product = Product.find(payment_params[:product_id])
    #  @user = current_user

      Stripe.api_key = "sk_test_nNbonBuIkaBf8JKbUu61Wahr"

      token = payment_params[:stripeToken]

      begin
        charge = Stripe::Charge.create(
          :amount => @product.price, #params[:product_price],
          :currency => "eur",
          :source => token,
          :description => payment_params[:stripeEmail]
        )

        if charge.paid
          Order.create(
            :product_id => @product.id,
            :user_id => user.id,
            :total => @product.price
          )
          MessageMailer.paid_success(user).deliver_now

          # check if user has already buy this product
          if ($redis.hget("ordered_by_#{user.id}:", "#{@product.id}"))
            # count how many times he ordered the same product
            $redis.hincrby("ordered_by_#{user.id}:", "#{@product.id}", 1)
          # if he orders the product for the first time
          else
            $redis.hset("ordered_by_#{user.id}:", "#{@product.id}", 1)
          end
        end

      rescue Stripe::CardError => e
        # the card has been declined
        body = e.json_body
        err = body[:error]
        flash[:error] = "Unfortunately, there was an error processing your payment: #{err[:message]}"
        redirect_to product_path(@product)
      end

  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  #before_action :convert_price_in_cents, only: [:create, :update]
  # GET /products
  # GET /products.json
  def index

    if params[:q]
      search_term = params[:q]
      # return our filtered list here
      @products = (Rails.env == 'production') ? Product.search_production(search_term) : Product.search_development(search_term)

    else
      @products = Product.where(public: true)
    end

    @special_offers = Product.special_offers
    logger.debug "------------"
    logger.debug "Current number of products in special_offers is #{@special_offers.size}"
    logger.debug "------------"
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @comments = @product.comments.order_paginate(params[:page])
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
    authorize! :edit, @product
  end

  # POST /products
  # POST /products.json
  def create
    updated_params = convert_price_to_cent(product_params)
    @product = Product.new(updated_params)
    @product.user_id = current_user.id
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    updated_params = convert_price_to_cent(product_params)
    respond_to do |format|
      if @product.update(updated_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def user_offers
    if(!current_user.admin?)
      @products  = Product.current_user_created(current_user.id)
    logger.debug "------------"
    logger.debug "Current user has #{@products.size} products "
    logger.debug "------------"
    else
      @products = Product.members_created
    end
  end

  def our_offers
    if(!current_user.admin?)
      redirect_to products_path
    else
      @products = Product.admin_created
    logger.debug "------------"
    logger.debug "Admins have #{@products.size} products "
    logger.debug "------------"
    end
  end

  def not_public_offers
      @products = Product.not_public_offers
    logger.debug "------------"
    logger.debug "Total number of pending offers is #{@products.size}"
    logger.debug "------------"
  end

  def special_offers
    @products = Product.special_offers
  end

  private

    def convert_price_to_cent(submitted_params)
      submitted_params[:price] = submitted_params[:price].to_f * 100 #convert to cents
      submitted_params
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :color, :price, :user_id, :public, :special_offer)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
  def cashe_key_for_products
    count = Product.count
    max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "products/all-#{count}-#{max_updated_at}"
  end
end

app/views/products/_errors.html.erb
<% if @product.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

    <ul>
    <% @product.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/products/_form.html.erb
  <%= form_for(@product) do |f| %>
  <%= render "errors"%>
  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control input-md", autofocus: true, placeholder: :name %><br>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control input-md", autofocus: true, placeholder: :description %><br>
  </div>
  <div class="form-group">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url, class: "form-control input-md", autofocus: true, placeholder: :image_url %><br>
  </div>
  <div class="form-group">
    <%= f.label :color %><br>
    <%= f.text_field :color, class: "form-control input-md", autofocus: true, placeholder: :color %><br>
  </div>
  <div class="form-group">
    <%= f.label :price %><br>
    <% if controller.controller_name == "products" && controller.action_name == "edit" %>
      <%= f.text_field :price, class: "form-control input-md", autofocus: true, placeholder: :price, :value => f.object.price.to_f / 100 %><br>
    <% else %>
      <%= f.text_field :price, class: "form-control input-md", autofocus: true, placeholder: :price %><br>
    <% end %>
  </div>
  <% if signed_in? && current_user.admin? %>
    <div class="form-group">
      <%= f.label :public %><br>
      <%= f.text_field :public, class: "form-control input-md", autofocus: true, placeholder: :public %><br>
    </div>
    <div class="form-group">
      <%= f.label :special_offer %><br>
      <%= f.text_field :special_offer, class: "form-control input-md", autofocus: true, placeholder: :special_offer %><br>
    </div>
  <% end %>
  <div class="actions">
    <%= f.submit class: "btn btn-default" %>
  </div>
<% end %>

app/views/products/_new_comment.html.erb
<% if signed_in? %>
  <h4 class="greeting">Add a review:</h4>
  <%= form_for([@product, @product.comments.build], class: "form-horizontal", remote: true) do |f| %>
  <div class="row">
    <div class="col-sm-6 col-xs-12 comment">
      <%= f.text_area :body, class: "form-control", placeholder: "Your comment" %>
    </div>
    <div class="col-sm-4 col-xs-12 comment">
      <%= f.label :rating %>
      <div class="rating"></div>
    </div>
  </div>
  <div>
    <%= f.submit "Submit", class: "btn btn-default" %>
  </div>
  <% end %>
<% end %>

app/views/products/_offer_title_wrapper.html.erb
<div class="col-sm-3 offer-title-wrapper">
  <h3>see special offer</h3>
  <h3>just today</h3>
  <a id="sp-offer-btn" class="btn btn-default" href="products/special_offers" role="button">open</a>
</div>

app/views/products/_product.html.erb
<div class="col-md-3 col-md-offset-0 col-sm-6 col-sm-offset-0 col-xs-8 col-xs-offset-2 product-holder">
  <% cache product do %>
    <%= link_to product, class: "scaffolded-link white" do %>
      <div class="product-wrapper">
        <div class="product-img-wrapper">
          <%= image_tag(product.image_url, class: "pics") %>
        </div>
        <div class="thin-bottom">
          <div class="product-name">
            <h4 class=""><%= product.name %></h4>
          </div>
          <div class="price">
            <span class="smaller"><%= product.price.to_f / 100 %> &euro;</span>
          </div>
        </div>

      <!--<p>Description: <%#= product.description %><p>
      <p>Color: <%#= product.color %></p>
      <p>Price: <%#= product.price %> &euro;</p>
      <p class="scaffolded-link"><%#= link_to 'Edit', edit_product_path(product), class: "scaffolded-link white" %> <%= link_to 'Show', product, class: "scaffolded-link white" %></p>-->
      <%#= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, class: "scaffolded-link white" %>
      </div>
    <% end %>
  <% end %>
</div><!-- /col -->

app/views/products/_special_offer.html.erb
<div class="item<%= " active" if special_offer == @special_offers.first %>">
  <%= image_tag(special_offer.image_url, class: "carusel-pics") %>
  <div class="carousel-caption">
    <%= special_offer.name %>
  </div>
</div>

app/views/products/edit.html.erb
<h1 class="page-title">Editing Product</h1>

<div class="panel panel-default">
  <div class="panel-body">
    <%= render 'form' %>

    <%= link_to 'Show', @product, class: "scaffolded-link" %> |
    <%= link_to 'Back', request.referer.present? ? request.referer : static_pages_index_path, class: "scaffolded-link" %>
  </div>
</div>

app/views/products/index.html.erb
<div class="container-fluid fixed bg-color-change">
  <div class="search-and-previous-page-wrapper">
    <!-- link to previous page -->
    <%= render "shared/previous_page" %>
    <%= render "shared/tablet_desktop_search_form" %>
  </div>
</div>
<h1 class="page-title title-down">Buy</h1>
<!-- separator-->
<%= render 'shared/separator' %>
<%= render "shared/alert" %>
<% if !@special_offers.empty? %>
  <div class="container mobile-tablet-hidden fade-out">

    <div class="row is-flex special-offer-wrapper">

      <%= render "offer_title_wrapper" %>

      <div class="col-md-6">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
          <!-- Indicators -->
          <ol class="carousel-indicators">
            <% @special_offers.each do |special_offer| %>
              <li data-target="#carousel-example-generic" class="<%= "active" if special_offer == @special_offers.first %>"></li>
            <% end %>
          </ol>
          <!-- Wrapper for slides -->
          <div class="carousel-inner" role="listbox">
            <% @special_offers.each do |special_offer| %>
              <%= render partial: "special_offer", locals: {special_offer: special_offer} %>
            <% end %>
          </div>
          <!-- Controls -->
          <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div><!-- /carousel -->
      </div>

      <%= render "offer_title_wrapper" %>
      <button type="button" class="btn btn-default close-offer">
        <i class="fa fa-times" aria-hidden="true"></i>
      </button>
    </div><!-- /special-offer -->
    <%= render "shared/separator" %>
  </div><!-- /container -->
<% end %>


<div class="container">
  <div class="row">
    <%# byebug %>
    <!-- renders _product.html.erb for each product -->
    <% cache (cashe_key_for_products) do %>
      <%= render @products %>
    <% end %>

  </div> <!-- /row -->
</div><!-- /container -->
<br>

<%#= link_to 'New Product', new_product_path, class: "scaffolded-link" %>

app/views/products/not_public_offers.html.erb
<h1 class="page-title">still not public</h1>
<%= render "shared/separator" %>
<div class="container">
  <div class="row is-flex">
    <!-- renders _product.html.erb for each product -->
    <%= render @products %>

  </div> <!-- /row -->
</div><!-- /container -->

app/views/products/not_public_products.html.erb
<div class="container">
  <div class="row is-flex">
    <!-- renders _product.html.erb for each product -->
    <%= render @products %>

  </div> <!-- /row -->
</div><!-- /container -->

app/views/products/our_offers.html.erb
<h1 class="page-title">Bike Berlin's Offers</h1>
<%= render "shared/separator" %>
<div class="container">
  <div class="row is-flex">
    <!-- renders _product.html.erb for each product -->
    <%= render @products %>

  </div> <!-- /row -->
</div><!-- /container -->

app/views/products/show.html.erb
<div class="container">
  <div class="row show-wrapper" data-product-id="<%= @product.id %>">
    <div class="col-md-4 col-md-offset-1 col-sm-6 col-xs-12">
      <%= image_tag(@product.image_url, class: "show-picture thumbnail img-responsive img-zoom", data_zoom_image: @product.image_url) %>
    </div>
    <div class="col-md-4 col-md-offset-2 col-sm-4 col-sm-offset-1 col-xs-12">
      <% cache @product do %>
        <h3 class="show-title">
          <%= @product.name %>
        </h3>
        <p><strong>Description:</strong>
        <%= @product.description %>
        <p><strong>Color:</strong>
          <%= @product.color %></p>
        <p>Average Rating: <div class="rated" data-score="<%= @product.average_rating %>"></div></p>
        <p><strong>Price:</strong>
          <%= @product.price.to_f / 100 %> &euro;
        </p>
      <% end %>
      <% if user_signed_in? %>
        <%= form_tag "/payments/create" do %>
          <%= hidden_field_tag(:product_id, @product.id) %>
          <%= render partial: "shared/stripe_checkout_button" %>
        <% end %>
      <% else %>
        In order to buy this product you have to <%= link_to "Login", new_user_session_path, class: "scaffolded-link" %>
      <% end %>
      <p><% if user_signed_in? && (@product.user_id == current_user.id || current_user.admin) %>
        <%= link_to 'Edit', edit_product_path(@product), class: "scaffolded-link" %> |
      <% end %></p>
      <%= link_to 'Back', request.referer.present? ? request.referer : static_pages_index_path, class: "scaffolded-link" %><br>
      <%= render "shared/alert" %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12">
      <%= render "new_comment" %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12">
      <div class="alert alert-info" style="display:none" role="alert">A new comment was posted!</div>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12">
      <%= render "comments" %>
      <%= will_paginate @comments %>
    </div>
  </div>
</div>

app/views/products/special_offers.html.erb
<div class="about-title-bg">
  <div class="page-title-wrapper">
    <div class="center-title">
      <h1>Special Offers</h1>
      <div class="hide-separator-on-small">
        <%= render "shared/separator" %>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <% @products.each do |special_offer| %>
    <div class="row show-wrapper">
        <div class="col-md-4 col-md-offset-1 col-sm-6 col-xs-12">
          <%= image_tag(special_offer.image_url, class: "show-picture thumbnail img-responsive") %>
        </div>
        <div class="col-md-4 col-md-offset-2 col-sm-4 col-sm-offset-1 col-xs-12">
          <h3 class="show-title">
            <%= special_offer.name %>
          </h3>
          <p><strong>Description:</strong>
          <%= special_offer.description %>
          <p><strong>Color:</strong>
            <%= special_offer.color %></p>
          <p>Average Rating: <div class="rated" data-score="<%= special_offer.average_rating %>"></div></p>
          <p><strong>Price:</strong>
            <%= special_offer.price / 100 %> &euro;</p>
            <% if user_signed_in? && (special_offer.user_id == current_user.id || current_user.admin) %>
              <%= link_to 'Edit', edit_product_path(special_offer), class: "scaffolded-link" %> |
            <% end %>
            <%= link_to 'Show', special_offer, class: "scaffolded-link" %> |
            <%= link_to 'Back', request.referer.present? ? request.referer : static_pages_index_path, class: "scaffolded-link" %><br>
            <%= render "shared/alert" %>
        </div>
    </div>
  <% end %>
</div>

app/views/products/user_offers.html.erb
<% if current_user.admin? %>
  <h1 class="page-title">Member's Offers</h1>
<% else %>
  <h1 class="page-title">Your Products</h1>
<% end %>
<%= render "shared/separator" %>
<%= render "shared/alert" %>
<% if @products.empty? %>
  <div class="panel panel-default">
    <div class="panel-body">
      <p>Currently you have no offers. Would you like to make one right now?</p>
      <%= link_to 'New Offer', new_product_path, class: "scaffolded-link white" %> |
      <%= link_to 'Back', request.referer.present? ? request.referer : static_pages_index_path, class: "scaffolded-link white" %>
    </div>
  </div>
<% else %>
  <div class="container">
    <div class="row is-flex">
      <!-- renders _product.html.erb for each product -->
      <%= render @products %>
    </div> <!-- /row -->
  </div><!-- /container -->
<% end %>