config/routes.rb
Rails.application.routes.draw do

  post 'payments/create'

  get 'products/special_offers'

  get 'products/our_offers'

  get 'products/not_public_offers'

  get 'products/user_offers'

  authenticate :user do
    resources :products, only: [:new, :create, :edit, :destroy]
  end

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => { :registrations => "user_registrations" }

  resources :users

  post 'messages/thank_you'

  get 'messages/new'

  get 'static_pages/repair'

  get 'static_pages/index'

  resources :products, only: [:index, :update, :show] do
    resources :comments
  end

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  root 'static_pages#index'

  mount ActionCable.server => '/cable'

  resources :orders, only:[:index, :show, :create, :destroy]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstApp</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
  </head>
  <!--<body class="
  <%# if (controller.controller_name == "static_pages" &&
  controller.action_name == "index")
  %>index-title-bg<%#end%>">-->
  <body>
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#myNavbar" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Bike Berlin</a>
        </div><!-- end navbar-header -->
        <div class="collapse navbar-collapse navbar-right" id="myNavbar">
          <ul class="nav navbar-nav">
            <li class="tablet-desktop-hidden">
                <%= render "shared/mobile_search_form" %>
            </li>
            <li><%= link_to "home", static_pages_index_path %></li>
            <li><%= link_to "about", static_pages_about_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Service <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "buy", products_path %></li>
                <li><%= link_to "sell", new_product_path %></li>
                <li><%= link_to "repair", static_pages_repair_path %></li>
                <li><%= link_to "special offers", products_special_offers_path %></li>
              </ul>
            </li>
            <li><%= link_to "contact", messages_new_path %></li>
            <li>
              <% if user_signed_in? && current_user.admin?%>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle lowercase" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %><span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "my account", "/users/#{current_user.id}" %></li>
                    <li><%= link_to "new offer", new_product_path %></li>
                    <li><%= link_to "Our offers", products_our_offers_path %></li>
                    <li><%= link_to "Members' Offers", products_user_offers_path %></li>
                    <li><%= link_to "not public", products_not_public_offers_path %></li>
                    <li><%= link_to("Logout", destroy_user_session_path, :method => :delete) %></li>
                  </ul>
                </li>
              <% elsif user_signed_in? && !current_user.admin? %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle lowercase" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %><span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "my account", "/users/#{current_user.id}" %></li>
                    <li><%= link_to "my orders", orders_path %></li>
                    <li><%= link_to "new offer", new_product_path %></li>
                    <li><%= link_to "my offers", products_user_offers_path %></li>
                    <li><%= link_to("Logout", destroy_user_session_path, :method => :delete) %></li>
                  </ul>
                </li>
              <% else %>
                <%= link_to("Login", new_user_session_path) %>
              <% end %>
            </li>
          </ul>
        </div><!-- end collapse navbar-collapse -->
      </div><!-- end container-fluid -->
    </nav> <!-- end navbar-->
    <%= yield %>


    <footer>
      <h4>&copy; 2016 Bike Berlin</h4>
    </footer>

  </body>
</html>